### ISSUE TITLE
OMEGATrackinMeasures_Diffusivity: trajectories that are unselected on the TB show up in graphs

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#249]
Even when trajectories are marked with the red x mark they show up in the graphs.

**Comment by strambc** [comment]
SAME BEHAVIOR FOR ALL TM plugins.

**Comment by Akramhar** [comment]
The RED / GREEN marker is only for visibility in SideBar atm. Let me know if you want to change it's behaviour. If you want a trajectory not to show up in the graphs you have to make a run without that trajectory selected.

**Comment by strambc** [comment]
I want the GREEN / RED mark on TB to be reflected everywhere.

**Comment by Akramhar** [comment]
should be solved in omega-0.35.

**Comment by strambc** [comment]
Works correctly with GLOBAL BAR graphs
Does not work with GOBAL LINE graphs
Works with LOCAL BAR graphs
**DOES NOT WORK WITH LOCAL LINE GRAPHS**

**Comment by strambc** [comment]
New issue created because now when a trajectory is de-selected on a browser the segment continue showing on the SIDE BAR overlay.

What disappears is the BOUNDING BOX. However the segment itself is still showing.
Same thing applies with Edited Trajectories overlay and to the Trajectories overaly.

New issue nr. #314

**Comment by Akramhar** [comment]
Can you produce screen shot of this issue please?
I tried to reproduce but I couldn't.
